version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./ai_interview_assistant.db
      - SECRET_KEY=supersecretkey123
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - APP_ENV=development
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=interview_assistant
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: 